import { useState, useMemo, useCallback } from 'react';
import { BookOpen, Copy, Check } from 'lucide-react';
import { BASELINE_DEFAULTS, MEASURES } from './constants/defaults';
import { calculateAll } from './utils/calculations';
import Header from './components/Header';
import BaselinePanel from './components/BaselinePanel';
import MeasureList from './components/MeasureList';
import ResultsDashboard from './components/ResultsDashboard';
import MethodologyModal from './components/MethodologyModal';

/**
 * Extract flat parameter values from BASELINE_DEFAULTS config objects.
 */
function getDefaultParams() {
  const params = {};
  for (const [key, config] of Object.entries(BASELINE_DEFAULTS)) {
    params[key] = config.value;
  }
  return params;
}

/**
 * Build initial measure states from MEASURES definitions.
 */
function getDefaultMeasureStates() {
  const states = {};
  for (const m of MEASURES) {
    states[m.id] = {
      enabled: false,
      value: m.hasSlider ? m.sliderConfig.default : null,
    };
  }
  return states;
}

export default function App() {
  const [params, setParams] = useState(getDefaultParams);
  const [measureStates, setMeasureStates] = useState(getDefaultMeasureStates);
  const [methodologyOpen, setMethodologyOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  // Recalculate results whenever params or measure states change
  const results = useMemo(
    () => calculateAll(params, measureStates),
    [params, measureStates]
  );

  const handleMeasureChange = useCallback((id, newState) => {
    setMeasureStates((prev) => ({ ...prev, [id]: newState }));
  }, []);

  const handleApplyPreset = useCallback((preset) => {
    if (!preset) {
      // Reset all
      setMeasureStates(getDefaultMeasureStates());
      return;
    }

    const newStates = getDefaultMeasureStates();
    for (const [id, config] of Object.entries(preset.measures)) {
      newStates[id] = {
        enabled: config.enabled,
        value: config.value ?? newStates[id].value,
      };
    }
    setMeasureStates(newStates);
  }, []);

  // Export scenario summary to clipboard
  const handleExport = useCallback(() => {
    const lines = [
      'NZ Fuel Reserve Impact Calculator — Scenario Summary',
      '═'.repeat(52),
      '',
      `Extended onshore reserve: ${results.extendedReserveDays.toFixed(1)} days (baseline: ${params.onshoreReserveDays})`,
      `Total demand reduction: ${(results.petrolDemandReduction * 100).toFixed(1)}%`,
      `Daily fuel saved: ${(results.combinedDailyFuelSaved / 1e6).toFixed(2)} million litres`,
      `Estimated annual economic cost: $${Math.abs(results.totalAnnualCost) >= 1e9 ? (results.totalAnnualCost / 1e9).toFixed(1) + 'B' : (results.totalAnnualCost / 1e6).toFixed(0) + 'M'}`,
      `Classification: ${results.tierLabel}`,
      '',
      'Active measures:',
    ];

    for (const m of MEASURES) {
      if (measureStates[m.id].enabled) {
        const r = results.perMeasure[m.id];
        const saving = r.dailyFuelSaved > 0
          ? ` → ${(r.dailyFuelSaved / 1e6).toFixed(2)}M L/day saved`
          : r.isDemandSmoothing ? ' → demand smoothing' : '';
        lines.push(`  • ${m.name}${saving}`);
      }
    }

    lines.push('', 'Generated by NZ Fuel Reserve Impact Calculator');

    navigator.clipboard.writeText(lines.join('\n')).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [results, params, measureStates]);

  return (
    <div className="app">
      <Header />

      <main className="main-layout">
        {/* Left column: controls */}
        <div className="controls-column">
          <BaselinePanel params={params} onParamsChange={setParams} />
          <MeasureList
            measureStates={measureStates}
            onMeasureChange={handleMeasureChange}
            onApplyPreset={handleApplyPreset}
            results={results}
          />
        </div>

        {/* Right column: results */}
        <div className="results-column">
          <ResultsDashboard results={results} baselineParams={params} />

          {/* Action buttons */}
          <div className="action-buttons">
            <button
              className="action-btn methodology-btn"
              onClick={() => setMethodologyOpen(true)}
            >
              <BookOpen size={18} />
              View methodology & assumptions
            </button>
            <button className="action-btn export-btn" onClick={handleExport}>
              {copied ? <Check size={18} /> : <Copy size={18} />}
              {copied ? 'Copied!' : 'Copy scenario summary'}
            </button>
          </div>
        </div>
      </main>

      <MethodologyModal
        isOpen={methodologyOpen}
        onClose={() => setMethodologyOpen(false)}
      />
    </div>
  );
}
